- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Action
      fail: 
        msg: "Oh no, I failed!"
      when: will_fail == "true"
